# Generated by Django 5.2.4 on 2026-03-07 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("articles", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="image",
            field=models.URLField(
                default="https://images.unsplash.com/photo-1505751172876-fa1923c5c528"
            ),
            preserve_default=False,
        ),
    ]
