# Generated by Django 5.2.4 on 2026-03-07 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("articles", "0002_article_image"),
    ]

    operations = [
        migrations.CreateModel(
            name="Service",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("test_name", models.CharField(max_length=200)),
                ("price", models.IntegerField()),
                ("tests_covered", models.TextField()),
                ("rating", models.FloatField()),
                ("image", models.URLField()),
            ],
        ),
    ]
