# Generated by Django 5.2.4 on 2026-03-08 21:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("articles", "0003_service"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Service",
        ),
    ]
