# Generated by Django 5.2.4 on 2026-03-08 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="test",
            name="image",
            field=models.ImageField(default="test.jpg", upload_to="tests/"),
            preserve_default=False,
        ),
    ]
