# Generated by Django 5.2.4 on 2026-03-08 21:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0002_test_image"),
    ]

    operations = [
        migrations.CreateModel(
            name="Collector",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("photo", models.ImageField(upload_to="collectors/")),
                ("phone", models.CharField(max_length=15)),
                ("rating", models.FloatField(default=4.5)),
            ],
        ),
        migrations.RemoveField(
            model_name="appointment",
            name="collector",
        ),
        migrations.RemoveField(
            model_name="appointment",
            name="test",
        ),
        migrations.CreateModel(
            name="Booking",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("phone", models.CharField(max_length=15)),
                ("address", models.TextField()),
                ("visit_time", models.CharField(max_length=50)),
                ("status", models.CharField(default="pending", max_length=20)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "test",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="services.test"
                    ),
                ),
                (
                    "collector",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="services.collector",
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="SampleCollector",
        ),
        migrations.DeleteModel(
            name="Appointment",
        ),
    ]
