# Generated by Django 5.2.4 on 2026-03-08 23:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0003_collector_remove_appointment_collector_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="visit_date",
            field=models.DateField(default=datetime.date(2026, 3, 9)),
            preserve_default=False,
        ),
    ]
